INSANE_SKIP_${PN}-dev = "ldflags"
INSANE_SKIP_${PN}-plugins-samples = "ldflags"
INSANE_SKIP_${PN}-resource = "ldflags"
INSANE_SKIP_${PN}-resource-samples = "ldflags"
INSANE_SKIP_${PN}-service = "ldflags"
INSANE_SKIP_${PN}-service-samples = "ldflags"
INSANE_SKIP_${PN}-tests = "ldflags"
