#! /usr/bin/make -f
# Author: Philippe Coval <philippe.coval@osg.samsung.com>
# ex: set tabstop=4 noexpandtab:
SELF?=${CURDIR}/rules/50-tasks.mk
explicit_file?=rules/45-explicit-local.mk
phony_file?=rules/80-phony-local.mk
config_file?=rules/10-config.mk
include_file?=rules/20-include.mk
local_file?=rules/04-machine-local.mk
machine_file?=rules/05-machine.mk

rules_files?=$(sort $(wildcard rules/??-*.mk))

gen_rules_files +=\
 ${config_file} \
 ${distro_file} \
 ${include_file} \
 ${phony_file} \
 ${explicit_file}
 ##eol

phony_rules_files?=$(subst ${phony_file},, ${rules_files})
welcome_delay?=5
machines_list?=$(shell ls rules/config/machine/ | sed -e 's|.mk||g' | grep -v '~' | sort)
bsp_list?=$(shell ls rules/config/bsp/ | sed -e 's|.mk||g' | grep -v '~' | sort)

.PHONY: rule/%

rule/default: GNUmakefile
	${MAKE} rule/override/build \
 || echo ${MAKE} rule/done/setup rule/override/cleanall rule/override/build
	${MAKE} rule/override/build

rule/build: rule/override/pre rule/override/all rule/override/post

rule/rebuild: rule/override/purge rule/override/build

rule/pre: ${explicit_file} ${phony_file} Makefile GNUmakefile
	@${MAKE} --no-print-directory rule/done/welcome
	@date

rule/post: GNUmakefile
	@echo "$@: $<"

rule/help: ${rules_files}
	@echo "# ${project} "
	@echo "# "
	@echo "# URL: ${url}"
	@echo "# "
	@echo "# Usage:"
	@echo "#  make [help] [longhelp] [default] [print]"
	@echo "#  make \$${MACHINE}"
	@echo "# "
	@echo "#  Where \$${MACHINE} is set to name of supported one among those:"
	@echo "#  ${machines_list}"
	@echo "# "
	@echo "#  Current machine is ${MACHINE}"
	@echo "# "
	@echo "# "

rule/welcome: GNUmakefile
	@echo "# "
	@echo "# Welcome, this is one time message"
	@${MAKE} rule/done/longhelp rule/override/print
	@echo "# If you want to build for a different machine than ${MACHINE}"
	@echo "# Press Crl+C during the next ${welcome_delay} seconds"
	@${MAKE} rule/override/pause/${welcome_delay}
	@echo "# Let's build for ${MACHINE}"

rule/pause/%: GNUmakefile
	sleep ${@F}

rule/force:
	@echo "$@: $<"

rule/longhelp: README.md rule/override/help
	@echo ""
	@cat $<

GNUmakefile: ${gen_rules_files} ${rules_files} ${SELF}
	@echo "#! /usr/bin/make -f" > ${@F}
	@for rule in ${rules_files} ; do echo "-include $${rule}" >> ${@F} ; done

rule/print-val/%:
	@echo "${@F}=${${@F}}"

rule/print: ${rules_files} GNUmakefile
	@echo "# Usage: make help"
	@echo ""
	@echo "# Existing rules :"
	@grep -o -e '^[^# 	]*:' $< \
 | grep -v '\$$' | grep -v '^rule/' | grep -v '\.mk:' | grep -v '^\.'
	@echo ""
	@echo "# Configuration / Environment:"
	@echo "# project_name=${project_name}"
	@echo "# branch=${branch}"
	@echo "# MACHINE=${MACHINE}"
	@echo "# SHELL=${SHELL}"
	@echo "# USER=${USER}"
	@echo "# bsp=${bsp}"
	@echo "# email=${email}"
	@echo "# os=${os}"
	@echo "# version=${version}"
	@echo "# DL_DIR=${DL_DIR}"
	@echo "# sources_dir=${sources_dir}"
	@echo "# cache_dir=${cache_dir}"
	@echo "# build_dir=${build_dir}"
	@echo "# image_dir=${image_dir}"
	@echo "# distro=${distro}"
	@echo "# conf_file=${conf_file}"
	@echo "# image=${image}"
	@echo "# images=${images}"
	@echo "# sources_name=${sources_name}"
	@echo "# sources_layers=${sources_layers}"
	@echo "# sources_layers_conf=${sources_layers_conf}"
	@echo "# machines_list=${machines_list}"
	@echo "# bsp_list=${bsp_list}"
	@echo "# write_dir=${write_dir}"
	@echo ""
	@echo "# More in rules/*.mk"

rule/warning:
	$(warning # log: ${@F}: ${ARGS})

rule/error:
	$(error # log: ${@F}: ${ARG})

rule/info:
	$(info log: ${@F}: ${ARG})

${task_dir}:
	mkdir -p $@


rule/patch: rule/override/sources_dir
	$(info no patch for $@)

rule/phony: ${phony_file}

${phony_file}: ${phony_rules_files}
	@mkdir -p ${@D}
	@echo '.PHONY: \' > $@
	@grep '^rule/.*:' rules/*.mk | grep -v '%' | cut -d: -f2| sort | sed -e 's|$$| \\|g' >> $@
	@echo ' #eol' >> $@

${explicit_file}: ${SELF} $(subst ${explicit_file},, ${phony_rules_files})
	@mkdir -p ${@D}
	@echo "# generated by ${<F}" > $@
	@grep -o 'rule/done/[^ /\[]*' rules/*.mk \
 | grep -v '%' | grep -v '.*/$$' | cut -d: -f2 | sort | uniq \
 | sed -e 's|\(.*\)$$|$${task_dir}/\1 \\|g' >> $@
	@echo -e ': $${rules_files}\n	@$${MAKE} rule/override/$${@F}\n	@mkdir -p $${@D}\n	@touch $${@}\n\n' >> $@

rule/explicit: ${explicit_file}

rule/done/%: ${task_dir}/rule/done/%
	$(info log: ${@}: rm "$<" to do it again)
	@ls -l $<

rule/make/%:
	$(info log: sub make to rescan files "$@")
	${MAKE} rule/${@F} ${ARGS}

rule/log/%: ${task_dir}
	mkdir -p ${task_dir}/${@D}
	script -e -c "${MAKE} rule/${@F}" ${task_dir}/$@

rule/all: GNUmakefile
	${MAKE} rule/done/configure
	-${MAKE} rule/done/print-images
	${MAKE} rule/override/image rule/done/list-images

rule/rules: ${rules_files}

${sources_dir}/${distro}: ${sources_dir} ${rules_files} rule/done/patch
	@ls -l ${@}/meta || make rule/error ARG="Please set distro var in $<"

rule/distro: ${sources_dir}/${distro}
	grep ${<F} rules/*.mk

${init_build_env}: ${sources_dir}/${distro}
	ls -l ${@D}

${build_dir}: ${init_build_env} rule/done/init_env
	ls ${<D}/${@F} || grep SHELL rules/*.mk && ln -fs ${@} ${<D}/${@F}
	ls ${@} || ln -fs ${<D}/${@F} ${@}
	$(info log: workaround a /bin/sh behaviour make sure to set SHELL=/bin/bash)

rule/init_env: ${init_build_env}
	mkdir -p ${build_dir}
	cd ${build_dir}/.. && ${source} ${<} ${build_dir}
	grep '^MACHINE.*' ${build_dir}/conf/local.conf

rule/init_build_env: ${init_build_env}
	ls $<

rule/bblayers: ${bblayers_file}
	ls $<

rule/build_dir: ${build_dir}
	ls $<

rule/configure-conf: rule/conf ${rules_files}
	grep -i MACHINE ${conf_file}

rule/configure-machine: ${conf_file}.mine
	cp -av $< ${conf_file}

rule/configure-bsp: ${conf_file} ${bblayers_file}
	@echo "$@: $<"

rule/images: ${task_dir}
	for image in ${images} ; do \
	make rule/override/all image=$${image} \
	|| echo "$${image}/$${machine}" >> ${task_dir}/fail.log ; \
	done ; \

rule/machines: ${task_dir}
	for machine in ${machines_list} ; do \
	make rule/overide/all MACHINE=$${machine} \
	|| echo "$${image}/$${machine}" >> ${task_dir}/fail.log ; \
	done ; \

rule/configs: ${task_dir}
	for machine in ${machines_list} ; do \
	make rule/overide/images MACHINE=$${machine} \
	|| echo "$${image}/$${machine}" >> ${task_dir}/fail.log ; \
	done ;

rule/clean:
	rm -rfv *~ .#*
	$(info make rule/{cleanall,distclean,purge} to clean more)

rule/cleanall: rule/override/clean
	rm -rfv ${build_dir}/conf ${task_dir}

rule/scm-setup-bsp: rule/override/scm-${scm}-setup
	@echo "# $@: $^"

rule/distclean: rule/override/cleanall rule/scm-${scm}-clean
	rm -rf ${build_dir}/tmp ${sources_dir} ${build_dir} ${task_dir}

rule/clean-bsp:
	$(info to be overriden in include/bsp/${bsp})

rule/purge: rule/override/distclean rule/override/scm-${scm}-cleanall
	rm -rf --  build* tmp

rule/build-packages: rule/override/build-packages
	$(info to overloaded $@)

rule/clean-packages: rule/override/clean-packages
	$(info to overloaded $@)

rule/rebuild-packages: rule/override/clean-packages rule/override/build-packages
	@echo "$@: $<"

rules/include/machine/%.mk:
	$(error please create $@)

rules/config/bsp/${bsp}/default.xml:
	$(error please create $@)

rule/reset:
	make GNUmakefile

rules/config/distro/${distro}/config.mk:
	@echo "#TODO: please add a distro and edit ${config_file}"
	exit 1

rules/config/bsp/${bsp}/config.mk:
	@echo "#TODO: please add a bsp and edit ${config_file}"
	exit 1
