.PHONY: \
rule/all \
rule/bblayers \
rule/bitbake/args \
rule/build \
rule/build-machines \
rule/build-machines \
rule/build-packages \
rule/clean \
rule/cleanall \
rule/cleanall/image \
rule/clean-bsp \
rule/clean-packages \
rule/compress \
rule/compress \
rule/conf \
rule/configs \
rule/configure \
rule/configure-bsp \
rule/configure-conf \
rule/configure-downloads \
rule/configure-machine \
rule/configure-scm-repo \
rule/default \
rule/distclean \
rule/distro \
rule/error \
rule/help \
rule/image \
rule/images \
rule/info \
rule/init_build_env \
rule/init_env \
rule/list/images \
rule/local/clean \
rule/machines \
rule/overide/clean-packages \
rule/overide/clean-packages/generic \
rule/overide/configure-conf \
rule/overide/help \
rule/overide/help \
rule/overide/packages \
rule/overide/patch \
rule/overide/patch/meta-oic/master \
rule/overide/patch/tizen-distro \
rule/overide/patch/tizen-distro/todo \
rule/overide/sources \
rule/patch \
rule/print-env \
rule/print/image \
rule/print/images \
rule/print/layers \
rule/purge \
rule/rebuild \
rule/rebuild-packages \
rule/repo \
rule/reset \
rule/reset \
rule/rules \
rule/scm-repo-clean \
rule/scm-repo-cleanall \
rule/scm-repo-dir \
rule/scm-repo-setup-bsp \
rule/scm-repo-sync \
rule/setup \
rule/setup-bsp \
rule/setup-bsp \
rule/setup/git \
rule/setup-os/centos \
rule/setup-os/debian \
rule/setup-os/fedora \
rule/setup-os/lsb \
rule/setup-os/opensuse \
rule/setup-os/ubuntu \
rule/show \
rule/show-recipes \
rule/sources \
rule/sub-configure-layers \
rule/sub-configure-rescan \
rule/sub-rule/layer/. \
rule/ui/args \
rule/ui/image \
rule/warning \
rule/wip \
rule/wip/help \
rule/wip/patch \
rule/wip/rebuild \
 #eol
