# Multimedia
CORE_IMAGE_BASE_INSTALL += "gstreamer1.0-meta-base"
CORE_IMAGE_BASE_INSTALL += "gstreamer1.0-meta-audio"
CORE_IMAGE_BASE_INSTALL += "gstreamer1.0-meta-video"
CORE_IMAGE_BASE_INSTALL += "gstreamer1.0-meta-debug"
CORE_IMAGE_BASE_INSTALL += "gstreamer1.0-plugins-good-meta"
CORE_IMAGE_BASE_INSTALL += "gstreamer1.0-plugins-base-meta"
CORE_IMAGE_BASE_INSTALL += "gstreamer1.0-plugins-ugly-meta"
CORE_IMAGE_BASE_INSTALL += "gstreamer1.0-plugins-bad-meta"
